mqtt:
  hostname: 127.0.0.1
  port: 1883 #defaults to 1883
  user: test
  password: test
deviceName: octopi
client_id: octopi
timezone: Europe/Paris
update_interval: 60 #Defaults to 60
sensors:
  temperature: true
  clock_speed: false
  disk_use: false
  memory_use: false
  cpu_usage: false
  load_1m: false
  load_5m: false
  load_15m: false
  net_tx: false
  net_rx: false
  swap_usage: false
  power_status: true
  last_boot: true
  hostname: true
  host_ip: true
  host_os: false
  host_arch: false
  last_message: false
  updates: false
  wifi_strength: false
  wifi_ssid: false
  ext_temperature_dht11: true
  ext_humidity_dht11: true
  ext_temperature_ds18b20: true
# external_drives:
    # Only add mounted drives here, e.g.:
    # Drive1: /media/storage
